// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsDP9YSDnQPz56xuTN1Aot8Gm-cu4iKck',
    appId: '1:545869663533:web:907ed43c25b5f5505317a4',
    messagingSenderId: '545869663533',
    projectId: 'samsar-first',
    authDomain: 'samsar-first.firebaseapp.com',
    storageBucket: 'samsar-first.appspot.com',
    measurementId: 'G-4XD6DDFESQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfW-ZWikq6WmA-uA8_Lt18SIWZoqDSxAY',
    appId: '1:545869663533:android:ab6ec8b73022dc7f5317a4',
    messagingSenderId: '545869663533',
    projectId: 'samsar-first',
    storageBucket: 'samsar-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBopMLzA_mA33d3Cwmwhn_Lr-kQOfVuEy0',
    appId: '1:545869663533:ios:2e9061c7220add065317a4',
    messagingSenderId: '545869663533',
    projectId: 'samsar-first',
    storageBucket: 'samsar-first.appspot.com',
    iosBundleId: 'com.samsar.samsar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBopMLzA_mA33d3Cwmwhn_Lr-kQOfVuEy0',
    appId: '1:545869663533:ios:2e9061c7220add065317a4',
    messagingSenderId: '545869663533',
    projectId: 'samsar-first',
    storageBucket: 'samsar-first.appspot.com',
    iosBundleId: 'com.samsar.samsar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsDP9YSDnQPz56xuTN1Aot8Gm-cu4iKck',
    appId: '1:545869663533:web:f777182ad4d734825317a4',
    messagingSenderId: '545869663533',
    projectId: 'samsar-first',
    authDomain: 'samsar-first.firebaseapp.com',
    storageBucket: 'samsar-first.appspot.com',
    measurementId: 'G-Z3SYQKMJ62',
  );
}
